name = "YAMLScript"
uuid = "c6519b1f-f61a-46f8-9c82-37138c212585"
authors = ["Ingy döt Net <ingy@ingy.net>"]
version = "0.0.16"

[deps]
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
